@hostname = localhost
@port = 8000
@host = http://{{hostname}}:{{port}}

###

GET {{host}} HTTP/1.1

###

POST {{host}}/tasks HTTP/1.1
content-type: application/json

{
	"description": "Andar com o cachorro"
}

###

GET {{host}}/tasks HTTP/1.1

###

PUT {{host}}/tasks/64fa499c28c0b3e9265a8fa8 HTTP/1.1
content-type: application/json

{
	"description": "Subir pro gitub",
	"done": false
}

###

DELETE {{host}}/tasks/64fa499c28c0b3e9265a8fa6 HTTP/1.1