@hostname = localhost
@port = 8000
@host = http://{{hostname}}:{{port}}
@taskId = 6510b1502a5ef8a6dc9781db

###

GET {{host}} HTTP/1.1

###

POST {{host}}/task HTTP/1.1
content-type: application/json

{
	"description": "Andar a com o cachorro"
}

###

GET {{host}}/task HTTP/1.1

###

PUT {{host}}/task/{{taskId}} HTTP/1.1
content-type: application/json

{
	"description": "Comer veneno"
}

###

DELETE {{host}}/task/{{taskId}} HTTP/1.1

###

PUT {{host}}/task/{{taskId}}/toggle HTTP/1.1
